name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Starting deployment..."
            cd /home/hamyvosugh/htdocs/www.hamyvosugh.com || exit 1
            echo "Pulling latest changes..."
            git pull origin main || exit 1
            echo "Installing dependencies..."
            npm install || exit 1
            echo "Building application..."
            npm run build || exit 1
            echo "Restarting PM2 process..."
            pm2 restart next-project || exit 1
            echo "Deployment completed successfully!"
