name: Deploy to Production

on:
  push:
    branches: 
      - main  
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Starting deployment..."
            cd ${{ secrets.WORK_DIR }} || exit 1
            echo "Current directory: $(pwd)"
            echo "Pulling latest changes..."
            git pull origin ${{ secrets.MAIN_BRANCH }} || exit 1
            echo "Installing dependencies..."
            npm install || exit 1
            echo "Building application..."
            npm run build || exit 1
            echo "Restarting PM2 process..."
            pm2 restart next-project || exit 1
            echo "Deployment completed successfully!"
